# Change these first
owner: IbereJr
repo: checkpages

sites:
#  - name: Site Pai
#    url: https://ibere.tizio.com.br
#  - name: Site Mãe
#    url: https://ideli.tizio.com.br
  - name: Curriculo
    url: https://cv.ibworks.com.br
  - name: Minecraft Bryan
    check: "tcp-ping"
    url: mcraft.ibworks.com.br
    port: 25565

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /checkpages
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Ibere JR
  introTitle: "**Monitoracao de Paginas** Status das minhas páginas"
  introMessage: Dados de [GitHub repository](https://github.com/iberejr/checkpages).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
#  See https://upptime.js.org/docs/configuration
