# Change these first
owner: iberejr
repo: checkpages

sites:
  - name: Google
    url: https://www.google.com
  - name: Site Pai
    url: https://ibere.tizio.com.br
  - name: Site Mãe
    url: https://ideli.tizio.com.br

status-website:
  #cname: demo.upptime.js.org
  #baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Ibere JR
  introTitle: "**Monitoracao de Paginas** Status das minhas páginas"
  introMessage: Dados de [GitHub repository](https://github.com/iberejr/checkpages).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
#  See https://upptime.js.org/docs/configuration
